// <auto-generated />
using System;
using FishingSessionsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FishingSessionsAPI.Migrations
{
    [DbContext(typeof(FishingDbContext))]
    [Migration("20260908170012_AddCatchEntity")]
    partial class AddCatchEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FishingSessionsAPI.Models.Catch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CaughtAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FishingSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FishingSessionId");

                    b.ToTable("Catches");
                });

            modelBuilder.Entity("FishingSessionsAPI.Models.FishingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FishingSessions");
                });

            modelBuilder.Entity("FishingSessionsAPI.Models.Catch", b =>
                {
                    b.HasOne("FishingSessionsAPI.Models.FishingSession", "FishingSession")
                        .WithMany("Catches")
                        .HasForeignKey("FishingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FishingSession");
                });

            modelBuilder.Entity("FishingSessionsAPI.Models.FishingSession", b =>
                {
                    b.Navigation("Catches");
                });
#pragma warning restore 612, 618
        }
    }
}
